### ISSUE TITLE
Ошибка при сборке под Mac

### ISSUE THREAD

**Issue by shkarupa-alex** [Koziev/GrammarEngine#10]
Make Error at CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /Users/alex/Downloads/GrammarEngine/src/demo/ai/solarix/ygres/mapper

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/Users/alex/Downloads/GrammarEngine/src/build/CMakeFiles/CMakeOutput.log".

**Comment by Koziev** [comment]
Спасибо за замечание,
закомитил забытый файл CMakeLists.txt в GrammarEngine/src/demo/ai/solarix/ygres/mapper
