### ISSUE TITLE
Ошибка при сборке русской словарной базы

### ISSUE THREAD

**Issue by vasvl123** [Koziev/GrammarEngine#14]
~/GrammarEngine/src/scripts/dictionary$ ./russian.sh 
rm: невозможно удалить '../../bin-linux64/*.db': Нет такого файла или каталога
rm: невозможно удалить '../../bin-linux64/*.bin': Нет такого файла или каталога
rm: невозможно удалить '../../bin-linux64/NGRAMS': Нет такого файла или каталога
Compiler version 14.18.11192 Standard Linux 4.15.0-34-generic x86_64  (build date Oct  2 2018)
SOLARIX Intellectronix project http://www.solarix.ru

../../dictionary.src/dictionary_version_pro.sol.....            0      lines OK
../../dictionary.src/gg_alphabets.sol...                        12     lines OK
../../dictionary.src/abc.sol...                                 38     lines OK
../../dictionary.src/latin_alphabet.sol....                     200    lines OK
../../dictionary.src/musical-symbols.sol.....                   13     lines OK
../../dictionary.src/english_alphabet.sol.......                261    lines OK
../../dictionary.src/russian_alphabet.sol......                 249    lines OK
../../dictionary.src/french_alphabet.sol....                    403    lines OK
../../dictionary.src/spanish_alphabet.sol......                 278    lines OK
../../dictionary.src/digits.sol.....                            31     lines OK
../../dictionary.src/specials.sol.....                          67     lines OK
../../dictionary.src/gg-russian-operations.sol.......           82     lines OK
../../dictionary.src/gg-english-operations.sol....              62     lines OK
../../dictionary.src/gg-french-operations.sol......             94     lines OK
../../dictionary.src/la.sol...                                  21     lines OK
../../dictionary.src/predef.sol.....                            124    lines OK
../../dictionary.src/sg_net_links.sol....                       206    lines OK
../../dictionary.src/sg_languages.sol....                       244    lines OK
../../dictionary.src/sg_main.sol....                            91     lines OK
../../dictionary.src/common_coordinates.sol....                 67     lines OK
../../dictionary.src/thesaurus_entries.sol....                  13     lines OK
../../dictionary.src/sg_rus_main.sol....                        592    lines OK
../../dictionary.src/sg_eng_main.sol....                        424    lines OK
../../dictionary.src/sg_fra_main.sol....                        207    lines OK
../../dictionary.src/sg_esp_main.sol....                        90     lines OK
../../dictionary.src/sg_jap_main.sol....                        320    lines OK
../../dictionary.src/sg_cn_main.sol.....                        99     lines OK
../../dictionary.src/sg_link_generators.sol....                 132    lines OK
../../dictionary.src/sg_common_thesaurus_tags.sol....           33     lines OK
../../dictionary.src/sg_delimiters.sol....
Error in line 43 column 7 of file ../../dictionary.src/sg_delimiters.sol
 entry "$@"  : ПУНКТУАТОР { flag:terminal_silent_noexport }
       ^^^^
Word entry can not have empty name
Error in line 43 column 7 of file ../../dictionary.src/sg_delimiters.sol
 entry "$@"  : ПУНКТУАТОР { flag:terminal_silent_noexport }
       ^^^^
Error parsing entry definition

Ошибка: 

Ошибка: There was an error while compiling the file ../../dictionary.src/dictionary

**Comment by Koziev** [comment]
Добрый день,
к сожалению, не могу воспроизвести - вытянул актуальное содержимое репозитория, скомпилировал все, собрал русскую словарную базу - ошибка не появилась.

**Comment by vasvl123** [comment]
Спасибо, попробую еще на другой машине

**Comment by vasvl123** [comment]
Получилось, прошу прощения за беспокойство. Вопрос можно закрывать.

**Comment by Koziev** [comment]
Понял, спасибо за проверку.
