### ISSUE TITLE
Как вызвать sol_Paraphrase в SDK для c#

### ISSUE THREAD

**Issue by ahvahsky2008** [Koziev/GrammarEngine#20]
Смотрю в сорсах. Для паскаля есть, а для шарпа не вижу. Подскажите как вызвать

**Comment by Koziev** [comment]
Привет,

эта функция (и весь функционал перефразировки/синонимизации) была исключена из SDK, давно уже.

**Comment by ahvahsky2008** [comment]
А в самих dll остались эти методы?

**Comment by Koziev** [comment]
>А в самих dll остались эти методы?

Нет, я убрал и код, и API для перефразировки из грамматического движка.

Эта штука (перефразировка) сейчас в другой теме возродилась, на новой алгоритмической базе. В чатботе, для аугментации датасетов. Может, руки дойдут выложить этот перефразировщик как отдельный проект.

**Comment by ahvahsky2008** [comment]
А что за проект? Мб я оттуда вытащу

**Comment by Koziev** [comment]
>А что за проект? Мб я оттуда вытащу

Это чатбот. Но в опубликованной версии перефразировки нет. Ее еще долго доводить до приемлемого уровня. И это будет, конечно, заточенный на диалоговые данные инструмент - короткие реплики, простой синтаксис.

**Comment by ahvahsky2008** [comment]
А на продажу что у вас тогда идёт?
