### ISSUE TITLE
Ошибка в спряжении глагола "осмелиться"

### ISSUE THREAD

**Issue by Koziev** [Koziev/GrammarEngine#6]
В файле rus_verbs_7036.sol, сместо Глагол_7084 надо написать 7036, проверять на глаголе осмелюсь-осмелишься-осмелиться.

**Comment by Veivan** [comment]
Открыл dictionary.src и не увидел rus_verbs_7036.sol

**Comment by Koziev** [comment]
Да, действительно, эта ошибка внесена в новой версии словарной базы, которую я еще не закомитил.
В репозитории спряжение для этого глагола корректное.
Пусть все-таки ошибка повисит, чтобы не забыть.

**Comment by Koziev** [comment]
Исправлено в текущих выложенных исходниках
